### ISSUE TITLE
Smart re-parsing of existing packages

### ISSUE THREAD

**Issue by GolezTrol** [utPLSQL/utPLSQL#114] opened 2016-12-02 10:01 UTC
`ut_suite_manager.run_cur_schema_suites_static` has this nice little parameter called `a_force_parse_again`. However, it seems to be all or nothing.

When I started to use utPLSQL, I found out that I created one test package for a unit of code (another package) that I wanted to test, and kept adding tests to that test package.

I think utPLSQL could be 'smart' in detecting whether or not I recompiled the package header of my test package since the last time it was parsed using `USER_OBJECTS.LAST_DDL_TIME`, and only in that case re-parse the package header.
I would still have to manually force reparsing when I add a new test suite, but changes to a suite or even dropping one could be detected this way.

This would cover the most common scenario of having a unit to test, having a test suite for it, and just making changes and additions to the test.

Benefits:
- Speed up running the tests, by only reparsing when needed.
- Speed up development, by automatically reparsing when needed.

**Comment by jgebal** [comment] 2016-12-02 10:05
That was done in annotations cache and probably could be added to the
project.
I think what we could do is create an interface for parser so we can decide
if we want to install and use cache or not.
@oasis. What do you think?

**Comment by oasis** [comment] 2016-12-02 10:36
What do I think? I think you've tagged the wrong guy! =P

**Comment by jgebal** [comment] 2016-12-02 10:38
@oasis Haha. Auto-correct on Android is playing tricks with me.
It was meant for @pazus

**Comment by jgebal** [comment] 2016-12-02 22:51
@GolezTrol Can you have a look at #57 - it was closed and not merged but I'm thinking about giving it a second chance with a bit different approach on integrating it.

**Comment by Pazus** [comment] 2016-12-05 07:32
Actually we do have cache right now. When the schema is parsed all it's suites are stored in `ut_suite_manager` cache per schema. The problem is 1) it doesn't invalidates on DDL, 2) it is not smart, the whole schema is parsed.

**Comment by GolezTrol** [comment] 2016-12-05 12:43
True. So instead of having `a_force_parse_again=Y/N`, I would be looking for `a_reparse=never/always/cache_changed/package_changed` or so. I'd imagine these possibilities:

1.  None: Just don't update the cache once the cache is made.
1.  Always/Force: Always update the entire cache, regardless.
1.  Cached package change: Check the last DDL of the packages that were cached before. Only reparse those packages when they have changed. Remove deleted test packages from the list.
1.  Any package change: Check the last DDL of all packages, like above, reparse modified test packages, but also, if there is a package that was added or modified, but wasn't cached before, parse it to see if it is a test package.

I can imagine that I would use mode 3 most of the time, because that allows me to modify the test package, and have my changes be picked up automatically, with reparsing still being fast.

Mode 4 would probably be slightly slower, although maybe not that much. It would only add benefit when you're adding extra test packages, but for that occasion you might also do a forced/full reparse manually.

While writing this, I wonder if the packages aren't recompiled when you compile the referenced code, because that would have a negative impact on the use for options 3 and 4. But I think only the test code would be affected by a code change, and the package header isn't recompiled in that case.. I'd have to test that to make sure.

**Comment by jgebal** [comment] 2016-12-05 13:05
Again option 3 with persistence is done in annotations cache. I'll bring it back to life and make it a separate module.

**Comment by Pazus** [comment] 2016-12-05 17:02
I imagine complex algorithm to define *how* the package was changed, imagine I've modified suitepackage value and added another package instead. As currently the parsing is quite fast I think we can start with the whole schema reparse if anything not from framework changed.

**Comment by Pazus** [comment] 2016-12-07 20:15
I've made a PR #117 addressing the issue.

**Comment by Pazus** [comment] 2016-12-14 18:58
Closed as the Pr was merged

**Closed by Pazus** 2016-12-14 18:58 UTC
Labels: enhancement, ready
