### ISSUE TITLE
First run after installation is not giving any output on 3.0.4

### ISSUE THREAD

**Issue by MickeVr** [utPLSQL/utPLSQL#514] opened 2017-11-15 14:24 UTC
Today I upgraded utplsql 3.0.3 to 3.0.4. The first run with Jenkins is not reporting any output.

Situation:

1. Jenkins resets a database schema with the code to test
2. Jenkins deploys utPlSql in this database schema
3. Jenkins deploys the unit tests in this schema, divided into two test suites
4. Each test suite is run by a separate call utPLSQL-sql-cli with the following options: @{connectstring} -p=@{schema}:@{packagesuite} -f=ut_documentation_reporter -s -f=ut_xunit_reporter -o=@{outputfile}

The first test suite that is executed results in a empty output file. Also no screen output is displayed. The second test suite is reporting results. Manually executing utPLSQL-sql-cli after this Jenkins job results in a non-empty output file.

Could this be an issue with the new caching mechanism? Or should I reset something? In version 3.0.3 the process described above worked fine.

**Comment by jgebal** [comment] 2017-11-16 00:56
It's an interesting issue.
I didn't observe this behaviour on our deployments.
Our Travis build is starting with a clean database, deploys latest release, deploys develop branch and then runs unit tests using last release version to test develop version.

I didn't observe that behaviour when developing the cache mechanism.
Will need to do some exploratory tests to see if i can reproduce this.
Even out Travis demo project runs fine the with clean database and fresh install.

Can you try to explore the issue on your end a bit more?

**Comment by jgebal** [comment] 2017-11-16 06:44
@MickeVr 
Can you provide info on: 
- database version and edition
- operating system of the DB

**Comment by jgebal** [comment] 2017-11-16 07:18
@MickeVr 
>The first test suite that is executed results in a empty output file. Also no screen output is displayed. The second test suite is reporting results. Manually executing utPLSQL-sql-cli after this Jenkins job results in a on-empty output file.

If you run:
- utPLSQL-sql-cli first_suite
- utPLSQL-sql-cli first_suite
- utPLSQL-sql-cli second_suite

Do you get expected results?

**Comment by MickeVr** [comment] 2017-11-17 09:37
Hi Jacek,

Oracle database is Oracle Database 11g Enterprise Edition Release 11.2.0.4.0 - 64bit Production, running on Windows. I will investigate the issue further.

**Comment by MickeVr** [comment] 2017-11-17 10:31
@jgebal 

Indeed, by running
    utPLSQL-sql-cli first_suite
    utPLSQL-sql-cli first_suite
    utPLSQL-sql-cli second_suite
I get my 'correct' output. The first run of the first suite does not execute anything, and acts in the same way as running it with a suitepath that does not exist on the schema.

**Comment by jgebal** [comment] 2017-11-26 21:05
Hi @MickeVr 
I took the following steps to reproduce.
1. Drop user containing utPLSQL
2. Install fresh utPSQL v3.0.4 into database.
3. Install tests into separate schema (UT3_TESTER)
4. run: 
  `ut_run UT3_TESTER/ut3@xe -p=UT3_TESTER -f=ut_documentation_reporter -s -f=ut_xunit_reporter -o=xunit.xml`

I see results on first run using `utPLSQL-sql-cli` as well as `utPLSQL-cli`.
I've tested on 11gR2XE, 12.1SE and 12.2SE

Please let me know if you're still facing this issue. I'm unable to reproduce.

**Comment by MickeVr** [comment] 2017-11-28 15:51
Hi @jgebal,

Suddenly the issue didn't occur any more, starting with a commit where we solved an occurrence of issue 516 (no new line between the suite and the unit test annotations). 

I removed a new line from an existing unit test and the issue reoccurs, so I conclude it is already a known issue.

Duplicate of 516

**Comment by jgebal** [comment] 2017-11-28 20:51
Ok, now that makes sense.
If you would look into log file of background process of sql-cli after the empty run, you would see the exception related to 3.0.4 restriction on package level annotations.

**Comment by jgebal** [comment] 2018-01-06 01:19
Related to #523 I'm closing this issue for now - it will be more obvious after additional logging on annotations is added.

**Closed by jgebal** 2018-01-06 01:19 UTC
