### ISSUE TITLE
utPLSQL does not execute test cases in a suite if there is no at least one empty line after suite annotation

### ISSUE THREAD

**Issue by alexeyhimself** [utPLSQL/utPLSQL#1009] opened 2019-10-22 08:59 UTC
**Describe the bug**
utPLSQL framework does not execute test cases in a suite if there is no at least one empty line after suite annotation (see screenshots)

**Provide version info**
v3.1.8.3190

**Information about client software**
PLSQL Developer

**To Reproduce**
1. Compile code without empty line after --%suite annotation:
```
create or replace package test_demo is
 
  -- %suite (Demo suite)
  -- %test (Demo test case success)
  procedure demo_test_pass;
  -- %test (Demo test case failure)
  procedure demo_test_failure;
 
end;
/
 
create or replace package body test_demo is
 
  procedure demo_test_pass is
  begin
    ut.expect(1).to_equal(1);
  end;
 
  procedure demo_test_failure is
  begin
    ut.expect(2).to_equal(1);
  end;
 
end;
/
```
2. Run utPLSQL:
```
select * from table(ut.run());
```

**Expected behavior**
Test cases in test suite have been executed:
```
Demo suite)
  Demo test case success (see below [.128 sec]
  Demo test case failure (see below [.018 sec] (FAILED - 1)

Failures:	 
  1) demo_test_failure
```

**Actual behavior**
```
Finished in .000013 seconds
0 tests, 0 failed, 0 errored, 0 disabled, 0 warning(s)
```

**Additional context**
If you add at least 1 empty line after --%suite annotation, then everything is fine:
```
create or replace package test_demo is
 
  -- %suite (Demo suite)

  -- %test (Demo test case success)
  procedure demo_test_pass;
  -- %test (Demo test case failure)
  procedure demo_test_failure;
 
end;
/
...
```

**Comment by lwasylow** [comment] 2019-10-22 09:01
Hi I think that's expected behaviour as we have to separate the suite annotations and tests annotations e.g displayname or context.

**Comment by jgebal** [comment] 2019-10-22 09:03
This is because suite annotation without empty line beconec annotation for procedure demo_test_pass

Suite level annotation s cannot be bound to procedure and so you need at least one empty line.

**Comment by pesse** [comment] 2019-10-22 09:05
I scanned the documentation, it's not explicitly stated. We maybe should state it explicitly, because yes, it is expected behavior.

We have several annotations that are valid for both, test and suite, therefore we need a distinction.

**Comment by alexeyhimself** [comment] 2019-10-22 09:12
When I started using utPLSQL, then I couldn't figure out why my test cases are not run. Only by a chance I found out that the reason was that missing line after --%suite. So, maybe explicit notion about this in documentation will help.

Thank you very much for fast response! I'll submit 2 more found issues within 30 minutes.

**Comment by jgebal** [comment] 2019-11-06 00:11
@alexeyhimself 
The documentation of annotations is now improved to be more explicit about right/wrong annotation placement.

https://github.com/utPLSQL/utPLSQL/blob/develop/docs/userguide/annotations.md#procedure-level-annotations
https://github.com/utPLSQL/utPLSQL/blob/develop/docs/userguide/annotations.md#package-level-annotations

I'm closing this issue as documentation fix is now part of develop branch and will be released soon.


Thank you for raising this issue. It highlights the gaps in documentation and helps us make it better.

**Closed by jgebal** 2019-11-06 00:11 UTC
Labels: documentation
