### ISSUE TITLE
finding issues with compiling test package in utplsql 3.18

### ISSUE THREAD

**Issue by anandsagar0126** [utPLSQL/utPLSQL#1021] opened 2019-11-09 19:53 UTC
I have successfully installed utplsql but now i am getting another issue. I have created at ut_ package and tried to compile
getting this error:
@c:\tempws\scripts\ADMIN\PackagesBody\ut_btwstr.pkb

LINE/COL ERROR

15/4 PL/SQL: Statement ignored
15/4 PLS-00201: identifier 'UTASSERT.EQ' must be declared
24/5 PL/SQL: Statement ignored
24/5 PLS-00201: identifier 'UTASSERT.ISNULL' must be declared
33/7 PL/SQL: Statement ignored
33/7 PLS-00201: identifier 'UTASSERT.ISNULL' must be declared
42/7 PL/SQL: Statement ignored
42/7 PLS-00201: identifier 'UTASSERT.ISNULL' must be declared
51/7 PL/SQL: Statement ignored
51/7 PLS-00201: identifier 'UTASSERT.EQ' must be declared

**Comment by jgebal** [comment] 2019-11-09 20:00
`UTASSERT` is not part of utPLSQL v3

What kind of test package is it that you try to compile?

**Comment by anandsagar0126** [comment] 2019-11-09 20:03
as given in the installation guide 
CREATE OR REPLACE PACKAGE ut_betwnstr
IS
   PROCEDURE ut_setup;
   PROCEDURE ut_teardown;
   
   PROCEDURE ut_betwnstr;
END ut_betwnstr;
/
CREATE OR REPLACE PACKAGE BODY ut_betwnstr
IS
   PROCEDURE ut_setup IS
   BEGIN
      NULL;
   END;
   
   PROCEDURE ut_teardown
   IS
   BEGIN
      NULL;
   END;
   PROCEDURE ut_betwnstr IS
BEGIN
   utAssert.eq (
      'Typical valid usage',
      BETWNSTR(
         STRING_IN => 'abcdefg',
         START_IN => 3,
         END_IN => 5
      ),
      'cde'
   );
    utAssert.isnull (
         'NULL start',
         BETWNSTR(
            STRING_IN => 'abcdefg',
            START_IN => NULL,
            END_IN => 5
         )
      );
      
      utAssert.isnull (
         'NULL end',
         BETWNSTR(
            STRING_IN => 'abcdefg',
            START_IN => 2,
            END_IN => NULL
         )
      );
      
      utAssert.isnull (
         'End smaller than start',
         BETWNSTR(
            STRING_IN => 'abcdefg',
            START_IN => 5,
            END_IN => 2
         )
      );
      
      utAssert.eq (
         'End larger than string length',
         BETWNSTR(
            STRING_IN => 'abcdefg',
            START_IN => 3,
            END_IN => 200
         ),
         'cdefg'
      );
END ut_BETWNSTR;
END ut_betwnstr;
/

**Comment by pesse** [comment] 2019-11-09 20:04
Can you provide which installation guide you are referring to? It looks like Version 2, which is very outdated and also very different to the current Version 3.

Maybe it would be good if you follow the "Getting Started" guide first:

https://github.com/utPLSQL/utPLSQL/blob/develop/docs/userguide/getting-started.md

Also look at our Resources-Section where you can find a ton of content about utPLSQL v3:
http://utplsql.org/resources/

You can also find a complete demo with utPLSQL v3 here:
https://github.com/utPLSQL/utPLSQL-demo-project

**Comment by anandsagar0126** [comment] 2019-11-09 20:06
http://utplsql.org/utPLSQL/v2.3.1/fourstep.html

**Comment by jgebal** [comment] 2019-11-09 20:06
@anandsagar0126 
It would be great if you could provide us with links to the documents you were referencing.
Maybe there is something we can do to avoid confusion in future.

Thanks
Jacek

**Comment by jgebal** [comment] 2019-11-09 20:08
You've downloaded and installed latest utPLSQL version but you're referencing to documentation for version that is de-supported for many years.
If you go to: http://utplsql.org/utPLSQL/ you will see full set of documentation links for different versions of utPLSQL.

**Comment by jgebal** [comment] 2019-11-09 20:09
This link might help to get you going:
http://utplsql.org/utPLSQL/v3.1.8/userguide/getting-started.html

**Comment by pesse** [comment] 2019-11-09 20:12
If you can share your way getting there or your thought process we might find ways to make it more clear which documentation to use. Or maybe you have a suggestion yourself?
I'm genuinely curious :)

**Comment by jgebal** [comment] 2019-11-14 09:29
The issue is related to the fact that you were referencing utPLSQL v2 documentation.
I'm closing the issue now - hope you're all sorted @anandsagar0126

**Closed by jgebal** 2019-11-14 09:29 UTC

**Comment by anandsagar0126** [comment] 2020-04-12 20:45
Hello @jgebal  I am looking to implement a use case where I would like to integrate utplsql with a visual studio IDE , run unit test cases and generate code coverage all using one wrapper procedure. Can you please help me with some steps or documentation that I can refer to? thanks a lot for your help in advance!
