### ISSUE TITLE
Assert object type to check for the exception occured

### ISSUE THREAD

**Issue by Pazus** [utPLSQL/utPLSQL#98] opened 2016-11-12 10:40 UTC
We need a special tool to assert correct exception was raised (code and/or errmsg)

**Comment by jgebal** [comment] 2016-11-12 10:53
I plan to implement it in the following way:
Create type `plsql_block` with constructor `plsql_block(clob/varchar2)` so we can pass in the block to be tested.

With this I can add assertion type `raise_exception`
This one can accept: 
- integer for error number
- varchar2 for like and varchar2 for escape_char
- you can also call it without parameters to check if any exception was/was not raised.

So the invocations would look like:
```
ut.expect( q'[begin raise_application_error(-20000, 'aaa'); end;]').to_( raise_exception(-20000) );
ut.expect( q'[begin raise_application_error(-20000, 'aaa'); end;]').to_( raise_exception('%aa%') );
ut.expect( q'[begin raise_application_error(-20000, 'a_a'); end;]').to_( raise_exception('%a\_a%','\') );

ut.expect( q'[begin NULL; end;]').not_to( raise_exception(-2000) );
ut.expect( q'[begin NULL; end;]').not_to( raise_exception() );
```

Additionally the ut_expectation can be extended so we can have this syntax availiable:
```
ut.expect( q'[begin NULL; end;]').to_raise_exception(-2000);
ut.expect( q'[begin NULL; end;]').not_to_raise_exception(-2000);
```

What do you think?

**Comment by Pazus** [comment] 2016-11-12 11:27
Then you have to deal with bind variables etc...
Maybe you can come up with the assertion mechanism one has to put in the exception block? Inside you might call `format_...` procedures to retrieve exception info.

**Comment by jgebal** [comment] 2016-11-12 15:12
It seems to me that we can go with the assertion syntax above or we can go with following syntax:
```sql
begin
  --the tested block
  a_tested_procedure();

  --assert on failure -> SQLCODE=0;
  ut.expect(sqlcode).to_( equal(-20001) );  
exception
  when others then
    --assert on failure or success -> SQLCODE != 0;
    ut.expect(sqlcode).to_( equal(-20001) );
end;
```

We can build a explicit matcher for exception in this case, but it doesn't bring much value as you can intercept and test for sqlcode using existing matchers.

The first solution is bad, as we will go into issues of bind variables, dynamic SQL etc.
The second one is not really a solution it's a coding pattern to achieve a goal.

We're struggling here with limitation of PL/SQL language.

Whichever we choose, we're not providing a real solution.
The real solution would be PL/SQL capability to pass in a block to execute like this:
```sql
declare
  l_block PLSQL_CODE_BLOCK; --this type does not exists in PL/SQL 
begin
  l_block := BEGIN a_tested_procedure(); END;
  ut.expect( l_block ).to_( raise_exception(-20000) );
end;
```

**Comment by Pazus** [comment] 2016-11-12 20:01
Lambdas in PL/SQL! Should we send that to oracle?:)

Agree, current to_equal and to_be_like on the exception block solve the problem.

**Comment by jgebal** [comment] 2016-11-12 20:14
Lambdas in PLSQL would be awesome!

**Comment by jgebal** [comment] 2016-11-12 20:36
This issue seems to be a duplicate of #81

**Comment by Pazus** [comment] 2016-12-07 20:21
I think we can close the issue.
Currently I agree that this kind of implementation is the most simple:
```
begin
  --the tested block
  a_tested_procedure();

  --assert on failure -> SQLCODE=0;
  ut.expect(sqlcode).to_( equal(-20001) );  
exception
  when others then
    --assert on failure or success -> SQLCODE != 0;
    ut.expect(sqlcode).to_( equal(-20001) );
end;
```

**Comment by jgebal** [comment] 2017-03-06 11:51
Closing, as it's currently achievable by.
```sql
declare
  v_sqlcode integer :=0;
begin
  begin
    --the tested block that is raising
    a_tested_procedure();
  exception 
    when others then 
      v_sqlcode := SQLCODE;
  end;
  ut.expect(v_sqlcode).to_( equal(-20001) );
end;
```

**Closed by jgebal** 2017-03-06 11:51 UTC
Labels: enhancement, task

**Comment by GolezTrol** [comment] 2018-04-04 10:28
Maybe this can be achieved by annotations? 

Something like: 

`%exception(-20001)`
