### ISSUE TITLE
Wrong result for get_suites_info when passing package name

### ISSUE THREAD

**Issue by PhilippSalvisberg** [utPLSQL/utPLSQL#977] opened 2019-07-16 05:28 UTC
**Describe the bug**

No result is returned when passing a package name to the `ut_runner.get_suites_info` function.

**Provide version info**
Information about utPLSQL and Database version, 
```sql
SQL> declare
  2    l_version varchar2(255);
  3    l_compatibility varchar2(255);
  4  begin
  5    dbms_utility.db_version( l_version, l_compatibility );
  6    dbms_output.put_line( l_version );
  7    dbms_output.put_line( l_compatibility );
  8  end;
  9  /
19.0.0.0.0
19.0.0


PL/SQL procedure successfully completed.

SQL> select substr(ut.version(),1,60) as ut_version from dual;

UT_VERSION                                                  
------------------------------------------------------------
v3.1.8.3161-develop                                         

SQL> select * from v$version;

BANNER
--------------------------------------------------------------------------------
BANNER_FULL
------------------------------------------------------------------------------------------------------------------------------------
BANNER_LEGACY                                                                        CON_ID
-------------------------------------------------------------------------------- ----------
Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production           
Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production                                                              
Version 19.2.0.0.0                                                                                                                  
Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production                    0


SQL> select * from nls_session_parameters;

PARAMETER                      VALUE                                                           
------------------------------ ----------------------------------------------------------------
NLS_LANGUAGE                   AMERICAN                                                        
NLS_TERRITORY                  SWITZERLAND                                                     
NLS_CURRENCY                   SFr.                                                            
NLS_ISO_CURRENCY               SWITZERLAND                                                     
NLS_NUMERIC_CHARACTERS         .'                                                              
NLS_CALENDAR                   GREGORIAN                                                       
NLS_DATE_FORMAT                DD.MM.RR                                                        
NLS_DATE_LANGUAGE              AMERICAN                                                        
NLS_SORT                       BINARY                                                          
NLS_TIME_FORMAT                HH24:MI:SSXFF                                                   
NLS_TIMESTAMP_FORMAT           DD.MM.RR HH24:MI:SSXFF                                          
NLS_TIME_TZ_FORMAT             HH24:MI:SSXFF TZR                                               
NLS_TIMESTAMP_TZ_FORMAT        DD.MM.RR HH24:MI:SSXFF TZR                                      
NLS_DUAL_CURRENCY              SF                                                              
NLS_COMP                       BINARY                                                          
NLS_LENGTH_SEMANTICS           BYTE                                                            
NLS_NCHAR_CONV_EXCP            FALSE                                                           

17 rows selected. 

SQL> select substr(dbms_utility.port_string,1,60) as port_string from dual;

PORT_STRING                                                 
------------------------------------------------------------
x86_64/Linux 2.4.xx 
```

**Information about client software**

not relevant

**To Reproduce**

1. install the current develop version

2. run this query:
```
SELECT *
  FROM TABLE(ut_runner.get_suites_info(upper('UT3_TESTER'), NULL))
 WHERE OBJECT_NAME = 'TEST_ANNOTATION_MANAGER';
```
it returns 17 rows.

3. run this query
```
SELECT *
  FROM TABLE(ut_runner.get_suites_info(upper('UT3_TESTER'), 'TEST_ANNOTATION_MANAGER'))
 WHERE OBJECT_NAME = 'TEST_ANNOTATION_MANAGER';
```
it returns no rows. Which is wrong. Should return 17 rows as well.

**Expected behavior**

The parameter `a_package_name` should work when passing a not null value.

**Comment by PhilippSalvisberg** [comment] 2019-07-16 05:38
This worked in v3.1.7.

**Comment by jgebal** [comment] 2019-07-16 07:31
Duplicate of #974

**Closed** 2019-07-16 08:16 UTC
Labels: bug
