### ISSUE TITLE
Coverage is not generated for object which does not contains any tests

### ISSUE THREAD

**Issue by adiic** [utPLSQL/utPLSQL#1049] opened 2020-02-25 04:10 UTC
I am not sure if it is by design, but let's say in our repository which contains 20 source + 10 test packages we ran the utplsql-cli pointing to those 30 source and test scripts. Note: there is only 10 test packages testing 10 of those source packages.

The coverage reporter is only producing report for those script which has tests. Let's say the average of these coverage is 80%. However, it should have been 40% considering half of the packages are not even been tested.

For the above, I am using utplsql-cli 3.1.8 and utplsql-core 3.1.7. The source and unit test schema is the same.

Is it possible to generate zero coverage for objects which was recognized by the CLI?

**Comment by jgebal** [comment] 2020-02-25 23:05
Hi @adiic 
This is by design.
When you're mapping project-files into utPLSQL, only code that is touched by tests will have coverage reported on it.
This is by design for few reasons:
- utPLSQL doesn't have a clear way of identifying which lines are cover-able (executable) and which are not (comments/declaration blocks/begin/end etc.)
- tools like Sonar do great job at doing this, so if a file is not touched (not covered at all), valid percentages will be reported

We could enhance this behavior in future but at this point in time it's not really feasible/easily achievable.

**Comment by jgebal** [comment] 2020-03-12 23:31
Note that in your example, the expected coverage would not be 40%.
The coverage % represents:
   Number of executable **lines** of code divided by number of **executed** lines of code

If you're not mapping project files, then you get schema-based coverage. That coverage will report all non-covered schema code as all-lines not covered.

When mapping files, we don't report in that way as tools like Sonar analyze and report coverage correctly on non-reported/non-covered files.

What type of report are you using on your project files? Where do you publish the reports?

**Comment by jgebal** [comment] 2020-03-12 23:32
A good addition would be to provide an override parameter to enforce reporting of:
- all non covered objects
- only covered objects

When option is not provided, default behavior would kick-in which is currently:
- for file-based coverage - report only on covered files
- for schema based coverage (no file mapping) - report all not-covered objects as 100% of lines not-covered.


Note that reporting 100% lines on non-covered schema objects is excessive and will drag your coverage down as all lines (including non-executable line) are reported as coverable/relevant/executable and not covered.

**Comment by jgebal** [comment] 2020-04-09 23:34
Related to: #1068 1068

**Comment by adiic** [comment] 2020-04-10 00:00
Hi @jgebal 
Thanks for continuing this as enhancement. I have managed to integrate utplsql with SonarQube so this is no longer an issue.

**Comment by jgebal** [comment] 2020-04-10 00:20
Great. I'll close this issue then - the alternative solution proposal is described in mentioned issue

**Closed by jgebal** 2020-04-10 00:20 UTC
Labels: discussion, enhancement, idea
