### ISSUE TITLE
Insufficient privilege to access object PUBLIC.UT on MBED3 database and Test not found on (MBED3, MBED3_TEST)  Database

### ISSUE THREAD

**Issue by LydiaAzzoug** [utPLSQL/utPLSQL#1216] opened 2022-07-05 10:31 UTC
HI, 
**Is your feature request related to a problem? Please describe.**
I installed the framawork sources on all my databases (I managed to do tests on 8 databases) but I still have 3 databases left. On these 3 bases I have the same problem which is the following:

Note: MBED3_TEST is a separate schema to put MBED3 tests (it's an image of MBED3)
<img width="192" alt="0Tests" src="https://user-images.githubusercontent.com/98126863/177308407-7baf64a2-3c38-420a-8155-25d7e33bd69c.PNG">
<img width="689" alt="MBED3_TEST" src="https://user-images.githubusercontent.com/98126863/177308451-4241d442-f0d5-4ce6-91be-cac449186218.PNG">

**Translation of test result**
alltests
  Test_ADDITION
    myfunction [,016 sec] (FAILED - 1)
 
Failures:
 
  1) myfunction
      ORA-04063: package body "MBED3_TEST.TEST_ADDITION" has errors
      ORA-06508: PL/SQL: program unit named: "MBED3_TEST.TEST_ADDITION" not found
      ORA-06512: at line 6
Finished in ,019472 seconds
1 tests, 0 failed, 1 errored, 0 disabled, 0 warning(s)
 

PL/SQL procedure completed.

Thank you in advance

**Comment by LydiaAzzoug** [comment] 2022-07-05 14:50
Thanks for your feedback, 
Concerning MBED3_TEST, you are right it is a compilation error(I'll look where the problem comes from). But on MBED3 there are no compilation errors  and I always have "No test found"

To solve the problem I executed this query "ALTER USER UT3 quota unlimited on UT_DATA;" but it didn't work

**Comment by jgebal** [comment] 2022-07-05 21:12
@LydiaAzzoug 

Reading what you have written is insufficient for me to know what is the problem.
Since you have succeeded on 8 databases and only see problem on remaining 3 databases, then the problem is most probably related to something you did or did not do on those 3 databases.

Since I don't know what you did differently on those 3 databases, I don't know how can I help you.

**Comment by jgebal** [comment] 2022-10-18 21:55
No reply from @LydiaAzzoug  - closing

**Closed by jgebal** 2022-10-18 21:55 UTC
Labels: question
