### ISSUE TITLE
ORA-00028: your session has been killed whenever we run ut_coverage_html_reporter()

### ISSUE THREAD

**Issue by himanshu2416** [utPLSQL/utPLSQL#1103] opened 2020-10-07 12:22 UTC
i am facing the issue when i execute the coverage report 

begin
  ut.run(ut_coverage_html_reporter());
end;
/

Error report -
ORA-00028: your session has been killed
ORA-00028: your session has been killed
00028. 00000 -  "your session has been killed"
*Cause:    A privileged user has killed your session and you are no longer
           logged on to the database.
*Action:   Login again if you wish to continue working.

Is there something from DBA which stops the execution or causing the deadlock.
Any hint on where i can find the exact issue which is causing the session to be stopped.

**Comment by jgebal** [comment] 2020-10-07 13:52
Is session gets automatically killed,  thee is a process dump that will indicate the root cause.

**Comment by himanshu2416** [comment] 2020-10-08 04:24
> Is session gets automatically killed, thee is a process dump that will indicate the root cause.

Yes

**Comment by himanshu2416** [comment] 2020-10-09 09:40
> Is session gets automatically killed, thee is a process dump that will indicate the root cause.

How do i get the process dump

**Comment by PhilippSalvisberg** [comment] 2020-10-09 09:52
@himanshu2416 you should find a link to the trace file in the alert.log of the database server. Please ask your DBA to support you. This issue is most probably unrelated to the utPLSQL framework. If you don't think so, please provide the information we asked for when you opened this issue. You see them [here](https://github.com/utPLSQL/utPLSQL/blob/develop/.github/ISSUE_TEMPLATE/bug_report.md) too. Thanks.

**Comment by pesse** [comment] 2020-11-12 20:02
Closing due to no answer

**Closed by pesse** 2020-11-12 20:02 UTC
