### ISSUE TITLE
UTPLSQL CLI Error: Detected Oracle driver stuck during Statement initialization after multiple retry

### ISSUE THREAD

**Issue by venkat-kasula** [utPLSQL/utPLSQL#1120] opened 2021-01-22 17:12 UTC
Hi All, 

When i m trying to execute UTPLSQL CLI , i m getting below error

--------------------------------------
TestRunner initialized
Running on utPLSQL v3.1.10.3349
Initializing reporters
Detected Oracle driver stuck during Statement initialization
**WARNING: Caught Oracle stuck during creation of Runner-Statement. Retrying (1)**

--------------------------------------
TestRunner initialized
Running on utPLSQL v3.1.10.3349
Initializing reporters
Detected Oracle driver stuck during Statement initialization
**WARNING: Caught Oracle stuck during creation of Runner-Statement. Retrying (4)**

After 4 retries, execution got terminated. Kinldy help me to resolve this issue.

**Comment by pesse** [comment] 2021-01-27 07:39
Hey @venkat-kasula , can you tell me if and how you were able to resolve the issue?

**Comment by venkat-kasula** [comment] 2021-01-28 07:23
@pesse  not yet.. i m not able to resolve the issue yet.

**Comment by pesse** [comment] 2021-02-04 12:49
Duplicate of #1121

**Closed by pesse** 2021-02-04 12:49 UTC
