### ISSUE TITLE
Realtime Reporter Timeout

### ISSUE THREAD

**Issue by michaelstaszewski** [utPLSQL/utPLSQL#955] opened 2019-06-23 15:54 UTC
I'm having a bit of difficulty with the real-time reporter in 3.1.7. I'm taking the default timeout value and it's timing out at 60 seconds every time. In 3.1.6 it was working fine. I'm not sure if the issue is in my code or the framework, but here's what I have. Using [the demo on YouTube](https://www.youtube.com/watch?v=80BMojrdCDk) and .\test\core\reporters\test_realtime_reporter.pkb from 3.1.6 as a guide I came up with the following.

Is this a fault in the framework or in my SQL? Thanks in advance.

#### Producer
```
DECLARE
    l_reporter_0    ut3.ut_realtime_reporter := ut3.ut_realtime_reporter ();
    l_reporters     ut_reporters;
    l_run_res       NUMBER;
    e_run_failure   EXCEPTION;
    PRAGMA EXCEPTION_INIT (e_run_failure, -20213);
BEGIN
    l_reporter_0.set_reporter_id ('10CDDEA461D24BE38CF9606C16B693AE');

    l_reporters := ut_reporters (l_reporter_0);

    BEGIN
        ut_runner.run (
            a_paths              =>
                ut_varchar2_list ('MSTASZEW.REALTIME_REPORTING_SUITE'),
            a_reporters          => l_reporters,
            a_fail_on_errors     => TRUE,
            a_coverage_schemes   => NULL,
            a_include_objects    => NULL,
            a_exclude_objects    => NULL);

        l_run_res := 1;
    EXCEPTION
        WHEN e_run_failure
        THEN
            l_run_res := 0;
    END;
END;
```

#### Consumer

```
SELECT item_type, text
  FROM TABLE (
           ut_output_table_buffer ('10CDDEA461D24BE38CF9606C16B693AE').get_lines ())
 WHERE TRIM (text) IS NOT NULL AND item_type IS NOT NULL;
```

**Comment by jgebal** [comment] 2019-06-23 16:06
Hi @michaelstaszewski 
The demo video by @PhilippSalvisberg isn't really right.
It's using internal object name to retrieve output data from reporter.
Instead of:
```sql
SELECT item_type, text
  FROM TABLE (
           ut_output_table_buffer ('10CDDEA461D24BE38CF9606C16B693AE').get_lines ())
 WHERE TRIM (text) IS NOT NULL AND item_type IS NOT NULL;
```

Use reporter methods to access output data.
```sql
select item_type, text
  from table( 
    ut3.ut_realtime_reporter('10CDDEA461D24BE38CF9606C16B693AE').get_lines()
  );
```

Internal output buffers should not be used.
In future, the privileges to access them can be removed in general.

Hope this helps.

**Comment by jgebal** [comment] 2019-06-23 16:07
We should probably do better job documenting public API's.

**Comment by jgebal** [comment] 2019-06-23 16:08
@michaelstaszewski - what are you building? Is it going to be commercial /open-source?

**Comment by michaelstaszewski** [comment] 2019-06-23 16:12
Thanks, @jgebal, I'll give that a shot. 

> what are you building?

Toad for Oracle integration. We had a call with you and Pazus a couple of months ago.

**Comment by michaelstaszewski** [comment] 2019-06-23 16:31
With that change I get ORA-06553. 

![image](https://user-images.githubusercontent.com/12683901/59979222-be3e9300-95b2-11e9-9fc8-1d4ccd64a834.png)

**Comment by PhilippSalvisberg** [comment] 2019-06-23 17:30
In the upcoming utPLSQL for SQL Developer version we use the public API to access the output of the realtime reporter. @jgebal is right. I really did it the wrong (unsupported) way in the video mentioned above. It's only working up to v3.1.4 because starting with v.3.1.5 the realtime reporter is using a dedicated output table.

Here are some excerpts of the code used in the upcoming SQL Developer extension. This should help you to understand how to use it for the time being.

[The PL/SQL block for the producer thread](https://github.com/PhilippSalvisberg/utPLSQL-SQLDeveloper/blob/issue_6/sqldev/src/main/java/org/utplsql/sqldev/dal/RealtimeReporterDao.xtend#L68-L83)

[The PL/SQL block for the consumer thread](https://github.com/PhilippSalvisberg/utPLSQL-SQLDeveloper/blob/issue_6/sqldev/src/main/java/org/utplsql/sqldev/dal/RealtimeReporterDao.xtend#L90-L97)

You have to make sure that the reporter used in the consumer session is properly initialized (with the reporter id used in the producer thread). See [here](https://github.com/PhilippSalvisberg/utPLSQL-SQLDeveloper/blob/issue_6/sqldev/src/main/java/org/utplsql/sqldev/dal/RealtimeReporterDao.xtend#L93).

**Comment by michaelstaszewski** [comment] 2019-06-23 19:47
Thank you, @PhilippSalvisberg. I'm able to use the reporter again.

**Comment by michaelstaszewski** [comment] 2019-06-24 16:46
get_lines() works, but rows come back in blocks of 100. get_lines_cursor() allows me to process rows as they become available for best UI updates. Is there a reason to avoid get_lines_cursor()? For real-time reporting I'm most concerned with UI updates and less so with maximum performance.

**Comment by jgebal** [comment] 2019-06-24 17:52
The 100 iis a size controlled by client oci/jdbc setting.
Try
```
 set arraysize=1 
```
Before running the query.
get_lines_cursor can be used as well but you need to handle closing the cursor is session both on success and exceptions.

**Comment by pesse** [comment] 2019-06-24 18:18
It's not possible (at least from java) to control the fetch size when using get_lines().
Therefore the cli uses get_lines_cursor(), which is actually SELECT where you can control the fetch size.

There are no real disadvantages of using get_lines_cursor(), I even enjoy the independence by using `select * from ...` - that way I don't need to adapt cli when we add new columns (as long as I don't need them).

**Comment by michaelstaszewski** [comment] 2019-06-24 18:34
I'm seeing the same, @pesse.

I'm using ODAC (OCI) and their FetchRows property controls arraysize and it's only functional with get_lines_cursor(). Similarly I execute my consumer and producer scripts in separate SQL*Plus sessions and SQL*Plus is also piping rows in blocks of 100. You can see the delayed response by the following sample suite. The post-run doesn't even arrive until after 5 seconds have elapsed.

#### Suite
```
CREATE OR REPLACE PACKAGE TEST_955
AS
  --%suite

  --%test
  PROCEDURE lengthy_test;
END;
/

CREATE OR REPLACE PACKAGE BODY TEST_955
AS
  PROCEDURE lengthy_test
  AS
  BEGIN
    DBMS_LOCK.sleep (5);
  END;
END;
/
```

Producer
```
DECLARE
  l_reporter_0    ut_realtime_reporter := ut_realtime_reporter ();
  l_reporters     ut_reporters;
  l_run_res       NUMBER;
  e_run_failure   EXCEPTION;
  PRAGMA EXCEPTION_INIT (e_run_failure, -20213);
BEGIN
  l_reporter_0.set_reporter_id ('D8A79E85915640A6A4E1698FDF90BA74');
  l_reporter_0.output_buffer.init ();

  l_reporters := ut_reporters (l_reporter_0);

  BEGIN
    ut_runner.run (
      a_paths              => ut_varchar2_list ('TEST_955'),
      a_reporters          => l_reporters,
      a_fail_on_errors     => TRUE,
      a_coverage_schemes   => NULL,
      a_include_objects    => NULL,
      a_exclude_objects    => NULL);

    l_run_res := 1;
  EXCEPTION
    WHEN e_run_failure
    THEN
      l_run_res := 0;
  END;
END;
/
```
#### Consumer

```
SET arraysize 1
VARIABLE report REFCURSOR

DECLARE
  l_reporter   ut_realtime_reporter := ut_realtime_reporter ();
BEGIN
  l_reporter.set_reporter_id ('D8A79E85915640A6A4E1698FDF90BA74');

  OPEN :report FOR SELECT t.item_type, t.text, rownum
                     FROM TABLE (l_reporter.get_lines ()) t;
END;
/
PRINT report
```

**Comment by pesse** [comment] 2019-06-24 18:39
I know I investigated this some months ago. If I remember correctly I stumbled over a forum post or part of documentation where it was stated that you can't control PL/SQL fetch size, but only SQL fetch size (I think this is general, but I'm very sure it's the case from Java).
`get_lines()` is PL/SQL fetch size only, `get_lines_cursor()` uses the SQL fetch size. The difference isn't that big so from my point of view there are no downsides in using `get_lines_cursor()`

**Comment by michaelstaszewski** [comment] 2019-06-24 18:42
Correction to my earlier arraysize statement, @pesse. I'm seeing arraysize being observed, however the first record in the data isn't returned to my app until 100 rows are available server side or the run has completed. This is just observation, but it takes a long time for the first record to become available when it shouldn't.

get_lines_cursor() works well so I'll carry on there. Thanks for the help.

**Comment by jgebal** [comment] 2019-06-24 19:14
This is odd @michaelstaszewski 
Out legacy `utPLSQL-sql-cli` (not supported anymore - replaced by `utPLSQL-cli`) was SQLPlus based and us used `set arraysize 1` successfully
It was using legacy approach to select from output buffer:

[This is the call](https://github.com/utPLSQL/utPLSQL-sql-cli/blob/develop/ut_run.sql#L420-L444) that was done in legacy sql-cli.

Seems that @PhilippSalvisberg  is also using cursor approach, though he is calling `get_lines()` in his [Java code](https://github.com/PhilippSalvisberg/utPLSQL-SQLDeveloper/blob/issue_6/sqldev/src/main/java/org/utplsql/sqldev/dal/RealtimeReporterDao.xtend#L90-L97)

**Comment by jgebal** [comment] 2019-06-24 19:20
Ah I see it now.
how about if you try:

**Consumer**
```
SET arraysize 1
WITH
  FUNCTION get_reporter RETURN ut3.ut_realtime_reporter IS
    l_reporter   ut3.ut_realtime_reporter := ut3.ut_realtime_reporter ();
  BEGIN
    l_reporter.set_reporter_id ('D8A79E85915640A6A4E1698FDF90BA74');
    return l_reporter;
  END;
SELECT t.item_type, t.text, rownum
  FROM TABLE (get_reporter().get_lines(1,1)) t;
```

**Comment by jgebal** [comment] 2019-06-24 19:25
I think we should think of enhancement to the reporter API to allow single-line reporter construction and consumption.
So that something like below would be possible:
```sql
SELECT * FROM 
   TABLE (ut_realtime_reporter().set_reporter_id ('D8A79E85915640A6A4E1698FDF90BA74').get_lines()) t;
```
or:
```sql
SELECT * FROM 
   TABLE (ut_realtime_reporter('D8A79E85915640A6A4E1698FDF90BA74').get_lines()) t;
```
The first option is easier to implement as it's a change to one base object.
The first option will also work with all external (3rd party) reporters as it does not require any changes to reporters themselves.
The second one is harder - need to create additional constructor for all reporters.

**Comment by michaelstaszewski** [comment] 2019-06-25 13:24
> It was using legacy approach to select from output buffer

That was my earlier approach until 3.1.7 and arraysize worked well there. I was poking around in the source and by no means am I an Oracle SQL/PLSQL developer, but I saw the bulk collect in there when trying to figure out what I had going on. It has a rownum limiter, but doesn't use the bulk collect LIMIT clause. Is that causing get_lines() to wait until the default 100 records are available?

I think your enhancement suggestion to get the report via simple SELECT would be fantastic.

I'll try your suggested code above here in a bit and report back.

**Comment by michaelstaszewski** [comment] 2019-06-25 13:49
> Ah I see it now.
> how about if you try:
> 
> **Consumer**
> 
> ```
> SET arraysize 1
> WITH
>   FUNCTION get_reporter RETURN ut_realtime_reporter IS
>     l_reporter   ut_realtime_reporter := ut_realtime_reporter ();
>   BEGIN
>     l_reporter.set_reporter_id ('D8A79E85915640A6A4E1698FDF90BA74');
>     return l_reporter;
>   END;
> SELECT t.item_type, t.text, rownum
>   FROM TABLE (get_reporter().get_lines()) t;
> ```

Same delay using my sample TEST_955 suite from above, but furthermore it's syntax new in 12c looks like and we support 11g still.

**Comment by jgebal** [comment] 2019-06-25 14:08
get_lines_cursor it is then :)

**Comment by PhilippSalvisberg** [comment] 2019-06-25 14:44
I have to look at this as well... I do no t “feel” a delay when running it from SQLDev. I’m using a thin driver and i set the [fetch size](https://github.com/PhilippSalvisberg/utPLSQL-SQLDeveloper/blob/issue_6/sqldev/src/main/java/org/utplsql/sqldev/dal/RealtimeReporterDao.xtend#L59) to 1.

**Comment by PhilippSalvisberg** [comment] 2019-06-28 20:57
I had a look at `get_lines()` and `get_lines_cursor()`. For me both methods work well from JDBC. My verdict. using `get_lines()` is safe.

A [`ut_realtime_reporter`](https://github.com/utPLSQL/utPLSQL/blob/v3.1.7/source/reporters/ut_realtime_reporter.tps#L1) is initialized with a [`ut_output_clob_table_buffer`](https://github.com/utPLSQL/utPLSQL/blob/v3.1.7/source/reporters/ut_realtime_reporter.tpb#L23). A `get_lines()` and a `get_lines_cursor()` call for an `ut_realtime_reporter` instance are implemented in the parent class [`ut_output_reporter_base`](https://github.com/utPLSQL/utPLSQL/blob/v3.1.7/source/core/types/ut_output_reporter_base.tpb#L59-L69).

**First implementation layer:**

[`ut_output_reporter_base.get_lines()`](https://github.com/utPLSQL/utPLSQL/blob/v3.1.7/source/core/types/ut_output_reporter_base.tpb#L59-L64) | [`ut_output_reporter_base.get_lines_cursor()`](https://github.com/utPLSQL/utPLSQL/blob/v3.1.7/source/core/types/ut_output_reporter_base.tpb#L66-L69)
-- | --
calls `ut_output_clob_table.get_lines()` and pipes all rows in a for loop | returns the result of `ut_output_clob_table.get_lines_cursor()`. This method is implemented in `ut_output_buffer_base`.

**Second implementation layer:**

[`ut_output_clob_table_buffer.get_lines()`](https://github.com/utPLSQL/utPLSQL/blob/v3.1.7/source/core/output_buffers/ut_output_clob_table_buffer.tpb#L68-L154) | [`ut_output_buffer_base.get_lines_cursor()`](https://github.com/utPLSQL/utPLSQL/blob/v3.1.7/source/core/output_buffers/ut_output_buffer_base.tpb#L38-L45)
-- | --
does all the magic. | `calls ut_output_clob_table_buffer.get_lines()`. Hence, `get_lines_cursor` is just a wrapper for `get_lines()`. A PL/SQL pipelined table function is always used.

If `get_lines_cursor()` works with a fetchSize of `1`, then querying from `get_lines()` should work as well. And with work I mean, that events are read by the consumer as soon as they are produced.

If this does not work, then I'm really interested in a reproducible test case.

**Comment by michaelstaszewski** [comment] 2019-07-01 13:00
@PhilippSalvisberg, I've provided a reproducible test case above. See my sample suite and the producer/consumer scripts to be executed in SQL*Plus. Using that example I do not get the pre-run event even until after the 5 secs dbms_lock.sleep has elapsed. Do you see differently using SQL*Plus on your machine? I cannot comment on JDBC, I use OCI.

**Comment by PhilippSalvisberg** [comment] 2019-07-01 20:03
Strange. I tried it based on your test case above. It works as expected. See:

![consumer_producer](https://user-images.githubusercontent.com/3883171/60463213-a9659d80-9c4b-11e9-9a3f-8ff8f3feb97a.gif)

First three events (pre-run, pre-suite, pre-test) are reported immediately. Then 5 seconds pause (due to the `dbms_lock.sleep(5)` in the test) and then the remaining events (post-test, post-suite, post-run) are reported. - Looks good.

**Comment by michaelstaszewski** [comment] 2019-07-03 13:46
Perhaps database version related. I do all of my initial development on a local 11g XE database when I don't need version specific features. Here are the scripts running in my dev environment.

![get_lines](https://user-images.githubusercontent.com/12683901/60596581-5426aa80-9d77-11e9-9711-cdc4ec3737f5.gif)

**Comment by pesse** [comment] 2019-07-03 13:57
Good idea! I develop on a 12.2 normally, so maybe this is an issue which has been solved with 18 or 19.
To wrap the function with a cursor is a workaround which definitely works on 12.1 and 12.2, though.

**Comment by PhilippSalvisberg** [comment] 2019-07-03 14:57
Good thinking. I have to test with earlier DB versions as well. Let you know the result.

**Comment by PhilippSalvisberg** [comment] 2019-07-03 20:32
This is really strange. 

I've tested it with SQL*Plus within a 11.2.0.4.190115 Docker container (from macOS). Works. Events are consumed immediately.

I tried it from Windows 10 using SQL*Plus 12.1.0.2.0 (32-bit Client/64-bit Client). And it works as well.

No problems from SQL Developer 19.1 connecting to the 11.2.0.4 database from macOS, Windows or Ubuntu. Events are available immediately, as expected.

I tried with utPLSQL v3.1.4 (first version with realtime reporter) and v3.1.8 (current develop version). Some result. No problems.

Maybe this is related to a specific version of SQL*Plus or Oracle Database or it is even platform specific (Windows). I'm running out of ideas. :-(

**Comment by PhilippSalvisberg** [comment] 2019-07-04 16:40
I can reproduce the problem it with Oracle Database 11.2 XE and SQL*Plus! When using this database version fetchSize will be ignored from Java as well. This really looks like an Oracle Database bug, which is has been fixed. However, the workaround is to use `get_lines_cursor()`. I changed the code in the SQL Developer extension accordingly. 

Thanks @michaelstaszewski  for reporting this issue.

**Closed by PhilippSalvisberg** 2019-07-04 16:40 UTC
Labels: question, support

**Comment by jgebal** [comment] 2019-07-13 02:33
I've made some small improvements (will be in 3.1.8).
So your producer and consumer can have reporters inline:
```sql
--main test run ( session 1 )
begin 
  ut_runner.run (
    ut_varchar2_list ('ut3_tester','ut3$user#'), 
    ut_reporters( 
      ut_realtime_reporter().set_reporter_id('d8a79e85915640a6a4e1698fdf90ba74')
    )
  );
end;
/
```
```sql
set arraysize 1
set pagesize 0
set long 400
set longchunksize 400

select
    ut_realtime_reporter()
      .set_reporter_id('d8a79e85915640a6a4e1698fdf90ba74')
      .get_lines_cursor()
  from dual;
```
```sql
set arraysize 1
set pagesize 0
set long 400
set longchunksize 400

select *
  from table(  
    ut_realtime_reporter()
      .set_reporter_id('d8a79e85915640a6a4e1698fdf90ba74')
      .get_lines()
  );
```

As with most enhancements, this will only work on 3.1.8 and above :(
