### ISSUE TITLE
Two ut packages with similar names cause issue

### ISSUE THREAD

**Issue by durrani** [utPLSQL/utPLSQL#468] opened 2017-08-23 15:31 UTC
I have two packages say: ut_name and ut_name_suffix

**Issue 1:**
exec ut.run('ut_name');

_Actual:_
This runs both packages.  

_Expected:_
Run only ut_name

**Issue 2:**
Calling individual procedure within ut_name gives error

exec ut.run('ut_name.my_proc');

_Actual:_
ORA-06512: AT "UTPLSQL.UT_SUITE_MANAGER", line 442
ORA-06512: AT "UTPLSQL.UT_SUITE_MANAGER", line 432
ORA-06512: AT "UTPLSQL.UT_SUITE_MANAGER", line 432
ORA-06512: AT "UTPLSQL.UT_SUITE_MANAGER", line 545
ORA-06512: AT "UTPLSQL.UT_RUNNER", line 76

ORA-20203: Suite not found

_Expected:_
Runs the procedure my_proc under ut_name

**Comment by jgebal** [comment] 2017-08-24 06:42
Thanks for reporting it @durrani

**Comment by Pazus** [comment] 2017-08-26 16:52
Hi @durrani !
I can't reproduce it on develop branch.
What version do you use?

**Comment by jgebal** [comment] 2017-08-28 07:08
@Pazus 
Did you try with 2 unit test packages: `ut_name` and `ut_name_suffix` without suitepath?
Can we simply add a test to confirm that this behavior is no longer there, when calling ut.run with test package name?

I've added #470, as the reported side-effect could actually be an interesting feature:
`ut.run('test_package*');` could be giving the reported behavior - execute by part of package name.

**Comment by jgebal** [comment] 2017-08-28 07:40
@Pazus , @durrani, I also cannot reproduce the behavior using our develop branch.
Testcase:

```sql
create or replace package ut_test as
--%suite

--%test
procedure aa;
end;
/

create or replace package ut_test_suffix as
--%suite

--%test
procedure aa;
end;
/
```
``sql
exec ut.run('ut_test');
```

```
ut_test
  aa [.014 sec] (FAILED - 1)
 
Failures:
 
  1) aa
      ORA-04067: not executed, package body "UT3_TESTER.UT_TEST" does not exist
      ORA-06508: PL/SQL: could not find program unit being called: "UT3_TESTER.UT_TEST"
      ORA-06512: at line 6
Finished in .019856 seconds
1 tests, 0 failed, 1 errored, 0 disabled, 0 warning(s)
```
Only the `ut_test` was called.

There was however an issue when calling by suitepath - fixed by @pazus

**Comment by durrani** [comment] 2017-08-28 09:04
Sorry for late reply.  Yes, I was also using suitepath. Thank you both.

**Closed** 2017-08-28 09:06 UTC
Labels: bug, in progress

**Comment by jgebal** [comment] 2017-08-31 10:34
@durrani you can now use v3.0.3 - fixed

**Comment by durrani** [comment] 2017-08-31 13:08
Thank you very much @jgebal @Pazus
