### ISSUE TITLE
UTPLSQL : Getting ORA-00600: internal error code 

### ISSUE THREAD

**Issue by Sriram-Sundar** [utPLSQL/utPLSQL#732] opened 2018-07-23 21:33 UTC
Created my own UTS (unit test schema user), separate from my application schema.
Successfully installed utplsql and was able to perform couple of testcases without issues
But when I try the below Test (Example from utplsql.org) **Getting ORA-00600: internal error code,** arguments: [qcsfbdnp:1], [L_EXCLUDE_XPATH], [], [2], [], [], [], [], [], [], [], []
when executing 
`BEGIN ut.run('testpkg'); end;`

`CREATE OR REPLACE package UTS.testpkg as
  --%suite()

   --%test
  procedure include_columns_as_csv;
end;
/
CREATE OR REPLACE package body UTS.testpkg as
procedure include_columns_as_csv is
    l_actual   sys_refcursor;
    l_expected sys_refcursor;
begin
    open l_expected for select rownum as rn, 'a' as "A_Column", 'x' SOME_COL from dual a connect by level < 4;
    open l_actual for select rownum as rn, 'a' as "A_Column", 'x' SOME_COL from dual a connect by level < 4;

    ut.expect( l_actual ).to_equal( l_expected );
end;  
end;
/`

**Comment by jgebal** [comment] 2018-07-23 21:40
What is your exact database version?
Do you have all most recent patches applied to your database?

Usually ORA-00600 requires a ticket to Oracle support.

Are you able to reproduce this error on every run?

Can you run a full trace on the session?

I might need help investigating that kind of error.

**Comment by Sriram-Sundar** [comment] 2018-07-25 16:54
Hi Jacek, Here are my responses
 
What is your exact database version?

> Oracle Database 12c Enterprise Edition Release 12.1.0.2.0 - 64bit Production

Do you have all most recent patches applied to your database? 

> Yes, all latest patches are applied.

Usually ORA-00600 requires a ticket to Oracle support.
Are you able to reproduce this error on every run? 

> Yes , every run. Tried 2 consecutive days with different options, still same error

Can you run a full trace on the session?
I might need help investigating that kind of error. 

> Trace file attached

[Development_ora_utplsql_tracefile.docx](https://github.com/utPLSQL/utPLSQL/files/2228787/Development_ora_utplsql_tracefile.docx)

I Would like to be a contributor in utplsql development, please let me know if I can be of any use.
I'm a Developer coding in PL/SQL for last 11 years.

Thanks! Sriram Sundar
Richmond,Virginia

**Comment by jgebal** [comment] 2018-07-25 18:56
@lwasylow - looks like that issue is related to inlude/exclude columns functionality.

**Comment by john-otoole** [comment] 2018-07-25 19:03
Hi, I noticed this issue and thought I have a poke around MOS to see if there's anything there for the ORA-00600 error. 

Looking at the trace file, it looks like its hitting the ORA-00600 for the "WITH" query on line 157 of UTS.UT_COMPOUND_DATA_HELPER. 
Might be related to the issue in MOS Doc Id 285899.1. For database 12.1.0.2 it suggests two possible bugs: 21373076 and 19670108. 

According to Doc Id 285899.1, the fix for 19670108 is first included in:
12.2.0.1 (Base Release)
12.1.0.2.3 (Apr 2015)  Database Patch Set Update (DB PSU)
12.1.0.2 Bundle Patch 7 (Apr 2015) for Engineered Systems / DB In-Memory (DBBP)
12.1.0.2 Patch 4 on Windows Platforms

And the fix for 21373076 is first included in:
12.2.0.1 (Base Release)
12.1.0.2.160419 (Apr 2016) Database Patch Set Update (DB PSU)
12.1.0.2.160119 (Jan 2016) Bundle Patch for Engineered Systems / DB In-Memory (DBBP)
12.1.0.2.160419 (Apr 2016) Bundle Patch for Windows Platforms
11.2.0.4.160531 (May 2016) Bundle Patch for Windows Platforms

Strange that nobody else has seen this with utPLSQL. Sriram what is the latest bundle patch you have applied to your 12.1.0.2 database?

John

**Comment by lwasylow** [comment] 2018-07-25 19:08
Im on it actually right now :) changing that line of code to exclude WITH and minimize transformations.
Problem is how I can test that ?? Sririam might have to switch to feature branch and test in his env once fix applied.

**Comment by jgebal** [comment] 2018-07-25 19:09
Since we can cee L_EXCLUDE_XPATH in exception my first bet would be to add colum aliases to the unused columns text returned by function:
https://github.com/utPLSQL/utPLSQL/blob/v3.1.1/source/expectations/data_values/ut_compound_data_helper.pkb#L79

**Comment by jgebal** [comment] 2018-07-25 19:12
I can't reproduce this either.
Would be great if Siriam could help us with testing the fix.

**Comment by Sriram-Sundar** [comment] 2018-07-26 14:41
Here is info on the Latest patch @john-otoole  asked

ACTION_TIME | ACTION | STATUS | DESCRIPTION | VERSION | PATCH_ID | BUNDLE_SERIES
---------------| --------- | ------- | ---------------| -----------| ---------- | -----------------
4/29/2018 9:09:24.143760 PM | APPLY | SUCCESS | DATABASE PATCH SET UPDATE 12.1.0.2.180417 | 12.1.0.2 | 27338041 | PSU

Sure I can test it, Can I uninstall now and download the latest version? let me know

**Comment by lwasylow** [comment] 2018-07-26 14:44
Please uninstall and downloaded a branch feature/cursor_improvments

**Comment by Sriram-Sundar** [comment] 2018-07-26 17:51
Installation Errored out  at **Line#60,76 Pkg Body UTS.ut_coverage**
Looks like unmatched Square brackets in regexp_like

Step1: uninstalled previous utplsql v3,
Step2: Downloaded Branch "feature/cursor_improvments"
Step3: ran @install.sql UTS

**Comment by jgebal** [comment] 2018-07-26 18:42
Can't be.
Our branches are continuously deployed and tested.
The branch is passing deployments and tests.
https://travis-ci.org/utPLSQL/utPLSQL/builds/408222580?utm_source=slack&utm_medium=notification

What is the error message you see?

**Comment by Sriram-Sundar** [comment] 2018-07-26 19:32
Sorry, Tried again. Installed successfully. 

Ran my uts.testpkg, 
Still getting the _ORA-00600:_ internal error code, arguments: [qcsfbdnp:1], [L_EXCLUDE_XPATH]
[UTS.TESTPKG sql and log.txt](https://github.com/utPLSQL/utPLSQL/files/2233314/UTS.TESTPKG.sql.and.log.txt)

**Comment by Sriram-Sundar** [comment] 2018-07-26 19:43
My other Testcases are fine, (both previous install & current branch )
[TEST_VVESTS_SMS_API sql and log.txt](https://github.com/utPLSQL/utPLSQL/files/2233355/TEST_VVESTS_SMS_API.sql.and.log.txt)

**see procedure include_columns_as_csv is commented

**Comment by jgebal** [comment] 2018-07-27 01:47
Do you have any non standard parameter values related to query optimizer/query rewrite?
That's one thing that comes to my mind at the moment.

**Comment by Sriram-Sundar** [comment] 2018-07-27 18:32
not that I know of, but I can check with my DBA

**Comment by jgebal** [comment] 2018-07-28 22:11
I had a chat with Gerald Venzl from Oracle.
He confirmed it's an Oracle issue (not documented amd not fixed yet).
Form our side @lwasylow is working on rewrite for that piece of code.
It it however strongly recommend that you report this issue to Oracle so they cam fix the bug on theit side and provide a patch for it.

**Comment by Sriram-Sundar** [comment] 2018-07-30 14:47
Thanks Jacek, I'll report this error to Oracle

**Comment by jgebal** [comment] 2018-11-06 07:57
HI @Sriram-Sundar -
Any feedback on this issue?
Did you get anything from Oracle?
I'm wondering if we can close this issue.

From our side - there are some changes coming in next versions.
They could potentially cause this exception to go away as we rework some of the heavy internal parts of framework.

**Comment by jgebal** [comment] 2018-11-28 08:34
@Sriram-Sundar 
Any feedback you can share?
Can you update to vesion 3.1.3 and see if the error is still there?

Thanks
Jacek

**Comment by jgebal** [comment] 2019-03-19 19:51
@Sriram-Sundar - since it is internal Oracle error, and there is nothing we can do to hel you, I'll close this issue.
I would appreciate if you could provide feedback if/when you get some additional info/patch from Oracle.

One more thing.
We will release 3.1.4 very soon. This version will have totally different approach to cursor data comparison.
It would be worth giving it a try once released.
You may even try our current develop version (3.1.4-develop).

**Closed by jgebal** 2019-03-19 19:51 UTC
Labels: discussion
