### ISSUE TITLE
Exception when comparing collections with utp.ut.expect

### ISSUE THREAD

**Issue by SElfimov** [utPLSQL/utPLSQL#1235] opened 2022-09-28 12:47 UTC
**Describe the bug**
When comparing collections converted to anydata with utp.ut.expect sometimes  we get this error, usually it works correctly.

**Provide version info**
utPLSQL 3.1.12

**Information about client software**
not applicable

**To Reproduce**

Run the below script
```sql

-- type creation
/*
create or replace type tp_r_ug_sportsman_invitation_result is object
(
    code              number(18),
    sportsman_name    varchar2(100),
    mobile_phone      varchar2(20),
    err_code          number,
    err_text          varchar2(4000)
);
create or replace type tp_t_ug_sportsman_invitation_result is table of tp_r_ug_sportsman_invitation_result;
*/

declare
    --records to compare
    --record 1
    v_sportsman_invitation_result  tp_t_ug_sportsman_invitation_result := tp_t_ug_sportsman_invitation_result
    (
        tp_r_ug_sportsman_invitation_result
        (
            code            => 1,
            sportsman_name  => 'sportsman_1',
            mobile_phone    => '79666666666',
            err_code        => 1,
            err_text        => null
        )
    );

    --record 2
    v_sportsman_invitation_exp  tp_t_ug_sportsman_invitation_result := tp_t_ug_sportsman_invitation_result
    (
        tp_r_ug_sportsman_invitation_result
        (
            code            => 1,
            sportsman_name  => 'sportsman_1',
            mobile_phone    => '79666666666',
            err_code        => 1,
            err_text        => null
        )
    );
begin
    --check rows in collections
    utp.ut.expect(v_sportsman_invitation_result.count, 'count collection')
          .to_equal(v_sportsman_invitation_exp.count);

    if v_sportsman_invitation_result.count = v_sportsman_invitation_exp.count then

        for i in 1..v_sportsman_invitation_result.count
        loop
            --check values of each part of a record
            utp.ut.expect(v_sportsman_invitation_result(i).sportsman_name, 'sportsman_name(' || i || ')')
                .to_equal(v_sportsman_invitation_exp(i).sportsman_name);
            utp.ut.expect(v_sportsman_invitation_result(i).mobile_phone, 'mobile_phone(' || i || ')')
                .to_equal(v_sportsman_invitation_exp(i).mobile_phone);
            utp.ut.expect(v_sportsman_invitation_result(i).err_code, 'err_code(' || i || ')')
                .to_equal(v_sportsman_invitation_exp(i).err_code);
        end loop;

        --compare 2 collections, here we get the exception
	utp.ut.expect(anydata.convertCollection(v_sportsman_invitation_result), 'Collections equal')
              .to_equal(anydata.convertCollection(v_sportsman_invitation_exp));

    end if;
end;
```

**See the exception:**

ORA-06502: PL/SQL: : numeric or value error: character string buffer too small
ORA-06512: на  "UTP.UT_DATA_VALUE_ANYDATA", line 98
ORA-06512: на  "SYS.DBMS_SQL", line 2146
ORA-06512: на  "UTP.UT_CURSOR_DETAILS", line 100
ORA-06512: на  "UTP.UT_DATA_VALUE_ANYDATA", line 84
ORA-06512: на  "UTP.UT_DATA_VALUE_ANYDATA", line 114
ORA-06512: на  "UTP.UT", line 33
ORA-06512: на  line 61

**Expected behavior**

We expect to get collections differences.

**Comment by jgebal** [comment] 2022-09-28 15:49
Please provide information about your database version and type (SE/EE/XE/Exadata/Cloud/on-prem)

**Comment by SElfimov** [comment] 2022-09-29 06:10
Hello
Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production
Version 19.13.0.0.0, EE exadata

**Comment by jgebal** [comment] 2022-09-29 13:53
The problem relates to the datatype we use in DBMS_SQL to describe cursor data.
Since you're using long object names (over 30 characters) that were not supported in older versions of oracle DB you code fails.

On our side, we need to make a fix with dynamic compilation.
So we would continue to use [DBMS_SQL.DESC_REC3](https://docs.oracle.com/database/121/ARPLS/d_sql.htm#ARPLS68213) on DB versions 11, 12.1 but would then use [DBMS_SQL.DESC_REC4](https://docs.oracle.com/en/database/oracle/oracle-database/12.2/arpls/DBMS_SQL.html#GUID-F7A93A26-F1D1-426C-97B5-EDD48D6F843E) for DB version 12.2 and above.


That should not b a massive change but it will be provided in some next version of utPLSQL.

Until then, the short-term solution would be to use object/collection type names that are shorter than 30 characters.

**Comment by SElfimov** [comment] 2022-09-29 18:03
[jgebal](https://github.com/jgebal), thank you for your answer and recomendation.

**Comment by SElfimov** [comment] 2022-09-29 18:05
[jgebal](https://github.com/jgebal), should I close the issue or you will close it after the fix ?

**Comment by jgebal** [comment] 2022-09-29 18:43
I will close it after a fix.
Thank you for reporting it and providing very good example that allowed for identification of the root cause

**Closed** 2022-10-17 20:45 UTC
Labels: bug
