### ISSUE TITLE
error stack seems to have gone awry

### ISSUE THREAD

**Issue by MrAsparagus** [utPLSQL/utPLSQL#1012] opened 2019-10-22 12:12 UTC
**Describe the bug**
Upgraded yesterday (to take advantage of context updates) and the stack trace on a failing test seems to have gone awry

**Provide version info**
Oracle XE 11.2
UTPLSQL v3.1.8.3190

**Information about client software**
TOAD

**To Reproduce**
Created the package  (see below)

exec ut.run('UT_FAIL') and get
  1) failing_test
      Actual: 4 (number) was expected to equal: 5 (number)
      00007FF9584FB8Aat "UT_CENTRAL.UT_FAIL", line 0 
      00007FF9584Fat "anonymous block", line 6840
      00007FF95E2D5Cat "SYS.DBMS_SQL", line 88
      00007FF9606B3Aat "UT3.UT_EXECUTABLE", line 98
      00007FF9606B3Aat "UT3.UT_EXECUTABLE", line 98
      00007FF9606B4Bat "UT3.UT_EXECUTABLE_TEST", line 48
      00007FF9606B4Bat "UT3.UT_EXECUTABLE_TEST", line 48
      00007FF9606B53Aat "UT3.UT_TEST", line 8
      00007FF9606B29Eat "UT3.UT_SUITE_ITEM", line 8
      00007FF9606Bat "UT3.UT_SUITE", line 6028
      00007FF9606BA0Eat "UT3.UT_RUN", line 8
      00007FF9606B29Eat "UT3.UT_SUITE_ITEM", line 8
      00007FFat "UT3.UT_RUNNER", line 960761878
      00007FFat "UT3.UT", line 960736158
      00007FFat "UT3.UT", line 960736158
      00007FFat "UT3.UT", line 960736158
      00007FF9584FAat "anonymous block", line 260
       
Finished in 0 seconds
1 tests, 1 failed, 0 errored, 0 disabled, 0 warning(s)

**Expected behavior**
  1) failing_test
      Actual: 4 (number) was expected to equal: 5 (number) 
      at "UT_CENTRAL.UT_FAIL", line 6 ut.expect( 2+2 ).to_equal( 5 );

**Example code**
CREATE OR REPLACE PACKAGE ut_fail
IS
  --%suite(failing test)

  -- %test(test to fail)
  procedure failing_test;
END;
/

CREATE OR REPLACE PACKAGE BODY ut_fail
IS
  procedure failing_test
  is
  begin
    ut.expect( 2+2 ).to_equal( 5 );
  end;
END;
/

**Additional context**
worked just fine yesterday with v3.1.7-develop
// just reinstalled v3.1.7-develop and expected behaviour returned

**Comment by jgebal** [comment] 2019-10-22 13:01
Duplicate of #1000
Already fixed in develop branch

**Comment by jgebal** [comment] 2019-10-23 23:14
@MrAsparagus - release 3.1.9 coming soon. I'll close this issue once released.

**Comment by jgebal** [comment] 2019-11-28 22:38
3.1.9 released and contains a fix for this issue - closing

**Closed by jgebal** 2019-11-28 22:38 UTC
