### ISSUE TITLE
Code Coverage does not refresh for next run

### ISSUE THREAD

**Issue by manomovva** [utPLSQL/utPLSQL#587] opened 2018-02-13 14:59 UTC
when I executed 
BEGIN
UT.RUN('UT3_USER',ut_coverage_html_reporter(),a_coverage_schemes => ut_varchar2_list('schema1'));
END;
It provides the code coverage for schema1 .
Next I executed the following but got same coverage html, schema2 packages are not displayed as 0 percent.
BEGIN
UT.RUN('UT3_USER',ut_coverage_html_reporter(),a_coverage_schemes => ut_varchar2_list('schema1','schema2'));
END;

**Comment by jgebal** [comment] 2018-02-13 15:08
Looks like a duplicate of #562 
That fix is part of next release.
Who not use utPLSQL-cli to run with coverage?
It's much more convenient.

**Comment by pesse** [comment] 2018-02-13 15:12
Even more so with next release, because it will provide the assets, too :)

**Comment by jgebal** [comment] 2018-03-16 10:22
This issue will be resolved with 3.1.0
Closing - duplicate of closed issue #562

**Closed by jgebal** 2018-03-16 10:22 UTC
