### ISSUE TITLE
Does utplsql support JUnit 5 format?

### ISSUE THREAD

**Issue by EGTBosch** [utPLSQL/utPLSQL#1256] opened 2023-06-12 06:51 UTC
As far as I know utplsql generates JUnit4 XML format reports (with ut_junit_reporter). On the other hand Bamboo (JUnit Parser plug-in) supports JUnit5 format XML file which looks a bit different compared to JUnit4 (e.g. JUnit 5 has no nested TestSuite elements which JUnit4 has) meaning that Bamboo is not able to parse a junit file generated with ut_junit_reporter (JUnit4).

Can anyone tell me if my observation is right? Are there plans to support JUnit5 in newer versions of utplsql? Does someone get utplsl generated xml get parsed in Bamboo?

**Comment by jgebal** [comment] 2023-06-12 08:33
You can use [TFS reporter](https://www.utplsql.org/utPLSQL/latest/userguide/reporters.html#tfs-vsts-reporter)

**Comment by jgebal** [comment] 2023-06-12 08:34
Duplicate of #1257

**Closed** 2023-06-12 12:54 UTC
