### ISSUE TITLE
unable to generate the coverage and corbertura xml  report 

### ISSUE THREAD

**Issue by srinivasaprabhu-java** [utPLSQL/utPLSQL#1218] opened 2022-06-23 15:43 UTC
Hi team ,  The coverage report generation is taking too long , nit sure why this is happened . 
All the test cases are completed , ut packages execution is completed . 
But the build gets time out at the steps when it generate the coverage xml and corbertura xml . 
I ma using below command . 

chmod +x ./LIB/utPLSQL-cli/bin/utplsql
echo "Reached here"
./LIB/utPLSQL-cli/bin/utplsql run "${db_user}/"${db_password}"@${db_url}" \
-t=600 \
-p=UT_RUN:COM.EXAMPLE.HH.DISTRIBUTED_DATA.UT_RUN \
-f=ut_documentation_reporter  -o=test_results.log  -s \
-f=ut_xunit_reporter          -o=test_results.xml     \
-f=ut_sonar_test_reporter     -o=hh_test_results_sonar.xml \
-f=ut_coverage_sonar_reporter -o=hh_coverage.xml    \
-f=ut_coverage_cobertura_reporter -o=cobertura.xml \
-source_path=database/code   -regex_expression="/(\w+)/(\w+)/(\w+)\.(\w{3})$"  -owner_subexpression=1   -type_subexpression=4   -name_subexpression=3 \
-test_path=database/UNIT_TESTING/UT_RUN/PACKAGE_BODIES -owner=UT_RUN \
--failure-exit-code=0
 

 
19:42:58   141) com.example.hh.distributed_data.[*******].ut_anlt_bond_pool_ext_pkg
19:42:58       Unable to perform automatic rollback after test suite. An implicit or explicit commit/rollback occurred in procedures:
19:42:59         [*******].ut_anlt_bond_pool_ext_pkg.ut_sec_no_hold_pool
19:42:59       Use the "--%rollback(manual)" annotation or remove commit/rollback/ddl statements that are causing the issue.
19:42:59  
19:42:59 Finished in 6294.744441 seconds
19:42:59 383 tests, 29 failed, 83 errored, 0 disabled, 141 warning(s)
19:42:59  
19:42:59 Build timed out (after 1,200 minutes). Marking the build as aborted.
13:56:11 Build was aborted
13:56:12 [BFA] Scanning build for known causes...
13:56:12 [BFA] No failure causes found
13:56:12 [BFA] Done. 0s
13:56:12 Finished: ABORTED

After  waiting for 10 hours the build fails .

My code structure : 

database/
	code/
		HH_USER/
			PACKAGE_BODIES/
			anlt_bond_pool_ext_pkg.pkb
			PACKAGE_SPECS/
			anlt_bond_pool_ext_pkg.pks
			
database/
	UNIT_TESTING/
	UT_RUN/
	PACKAGE_BODIES/
	ut_anlt_bond_pool_ext_pkg.pkb
	PACKAGE_SPECS/
	ut_anlt_bond_pool_ext_pkg.pks
			
			
like HH_USER is a db schema, we have 20 different schema i.e. 20 different folders under the "code" folder. But all ut code is  under  one schema UT_RUN.		

When i run the same code for a suite with only 2/3 ut packages , it works fine .
not sure what am i missing here.

**Comment by jgebal** [comment] 2022-07-14 20:04
I suspect that the problem is related to fact that you have 20 db-schemas in your repository.
When you run a set of tests, the coverage will be gathered on all 20 schemas.

I'm not sure how big your codebase is, but it might prove to be too big to handle.
Could you perhaps try to run it for single schema only and see if the coverage is gathered successfully?


What version of utPLSQL framework are you using?
What version of database are you working on? Is it a multitenant DB?

**Comment by jgebal** [comment] 2022-10-18 21:57
no reply from @srinivasaprabhu-java - closing.

**Closed by jgebal** 2022-10-18 21:57 UTC
Labels: question
