### ISSUE TITLE
RunningTime annotation

### ISSUE THREAD

**Issue by AlexTM89** [utPLSQL/utPLSQL#1188] opened 2022-02-16 06:29 UTC
**Is your feature request related to a problem? Please describe.**
My team need to control execution time of some tests, i.e. if test runs more than X second (X is param) then it's not passed.

**Describe the solution you'd like**
We would like that solution will be if form of annotation.

Here is code sample
`create or replace package utp_sample is`

`--%suite(utp_sample)`
`--%test(sample_test)`
`--%runningtime(10)`
`procedure test;`
`....`

and here is sample result
`utp_sample`
`  sample_test [12.218 sec] (FAILED - 1)`
` `
`Failures:`
` `
`  1) test`
`      "Max running time exceeded: expected 10, actual is 12"`
`      at "PRS.UTP_SAMPLE.TEST", line 6 ...`

**Describe alternatives you've considered**
Here is workaround:

create two vars: start_ts and end_ts with type timestamp(...) or date
before first operation in test we set start_ts := systimestamp;
after last operation we set end_ts := systemtimestamp;
then calculate diff and compare with some constant. If diff more than constant - throw an error or use
ut.except(1).to_equal(2) with custom message;

**Comment by jgebal** [comment] 2022-02-16 07:29
This is a duplicate of: #698
Please read through it and add your comments there, so we can consider implementing.

**Closed by jgebal** 2022-02-16 07:29 UTC
